server:
  port: 10120
spring:
  profiles:
    active: dev
  application:
    name: miniprogram
ops:
  api-version: v1
#图片检测nuc
photo:
  addr: http://nuc32.huigouiot.com
  userName: 1@163.com
  password: huigou2019
open:
  # 此服务是否运行定时任务
  scheduling: false
  # 是否启动系统性能监控
  monitor: false

#微信小程序
wx:
  mini:
    appId: wxdb6dad1f417f13e6
    secret: 59cc04267a0f24ea879d4acdad955cf7
    code2Session_api: https://api.weixin.qq.com/sns/jscode2session?appid=${wx.mini.appId}&secret=${wx.mini.secret}&js_code=%s&grant_type=authorization_code
